version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    volumes:
      - db:/var/lib/postgresql
    environment:
      POSTGRESQL_USER: tatuiapp
      POSTGRESQL_PASSWORD: tatuiapp
      POSTGRESQL_DATABASE: tatuiapp
    ports:
      - "5432:5432"
    networks:
      - tatui-network

networks:
  tatui-network:
    driver: bridge

volumes:
  db:
